# docker-compose.yml
version: '3.9'

services:
  attendance-api:
    build: .
    container_name: daily-qr-attendance
    restart: unless-stopped
    ports:
      - "80:8000"
    volumes:
      - db-data:/app           # This mounts the whole folder with correct permissions
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - attendance-net

volumes:
  db-data:                       # Named volume = persistent + correct permissions

networks:
  attendance-net:
    driver: bridge