version: '3.9'

services:
  attendance-api:
    build: .
    container_name: daily-qr-attendance
    restart: unless-stopped
    ports:
      - "80:8000"
    volumes:
      - ./data:/app                    # All files (including DB) saved on host
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  data: